services:
  books-recommendation-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-recommendation-agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


    env_file:
      - .env
    volumes:
      - ./books-recommendation-agent:/app/books-recommendation-agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - books-recommendation-agent-network


networks:
  books-recommendation-agent-network:
    driver: bridge
